const npmTest = require("currency-conjugates");
let number = 12.22;
const rubleKopeika = npmTest.rubleKopeika(number);
console.log(rubleKopeika);
const dollarCent = npmTest.dollarCent(number);
console.log(dollarCent);
const euroEuroCent = npmTest.euroEuroCent(number);
console.log(euroEuroCent);
const yenJapan = npmTest.yenJapan(number);
console.log(yenJapan);
const yuanChina = npmTest.yuanChina(number);
console.log(yuanChina);
